image: docker.mshop.csolab.ru/mshop-worker-python3:1.1

stages:
  - build

publish:
  tags:
    - mshop
  stage: build
  script:
    - export VERSION=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
    - python3.6 setup.py sdist bdist_wheel
    - python3.6 -m twine upload --repository-url ${PYPI_PUBLISH_URL} dist/* -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}
